#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Fri Nov 15 17:11:25 +03 2024
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto db52341a2abc4a64be4299ac54af1ce0 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot adder_subtractor_4bit_tb_behav xil_defaultlib.adder_subtractor_4bit_tb xil_defaultlib.glbl -log elaborate.log"
xelab -wto db52341a2abc4a64be4299ac54af1ce0 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot adder_subtractor_4bit_tb_behav xil_defaultlib.adder_subtractor_4bit_tb xil_defaultlib.glbl -log elaborate.log

