#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Nov 15 17:11:29 +03 2024
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim adder_subtractor_4bit_tb_behav -key {Behavioral:sim_1:Functional:adder_subtractor_4bit_tb} -tclbatch adder_subtractor_4bit_tb.tcl -log simulate.log"
xsim adder_subtractor_4bit_tb_behav -key {Behavioral:sim_1:Functional:adder_subtractor_4bit_tb} -tclbatch adder_subtractor_4bit_tb.tcl -log simulate.log

